import { ILessonQuestion } from '../services/lesson.service';

export const PHONETICS_QUESTIONS: Map<string, ILessonQuestion[]> = new Map<string, ILessonQuestion[]>([
  ['1', [
    { question: 'what-is-phonetic.m4a', lessonUnit: 'ch-chợ', answer: 'Ch.m4a', image: 'ch.png' },
    { question: 'what-is-phonetic.m4a', lessonUnit: 'kh-khế', answer: 'Kh.m4a', image: 'kh.png' },
    { question: 'what-is-phonetic.m4a', lessonUnit: 'gh-ghế', answer: 'Gh.m4a', image: 'gh.png' },
    { question: 'what-is-phonetic.m4a', lessonUnit: 'ng-ngủ', answer: 'Ng.m4a', image: 'ng.png' },
    { question: 'what-is-phonetic.m4a', lessonUnit: 'ngh-nghệ', answer: 'Ngh.m4a', image: 'ngh.png' },
    { question: 'what-is-phonetic.m4a', lessonUnit: 'th-thỏ', answer: 'Th.m4a', image: 'th.png' },
    { question: 'what-is-phonetic.m4a', lessonUnit: 'nh-nhà', answer: 'Nh.m4a', image: 'nh.png' },
    { question: 'what-is-phonetic.m4a', lessonUnit: 'tr-tre', answer: 'Tr.m4a', image: 'tr.png' },
    { question: 'what-is-phonetic.m4a', lessonUnit: 'ph-phở', answer: 'Ph.m4a', image: 'ph.png' },
    { question: 'what-is-phonetic.m4a', lessonUnit: 'gi-giá vẽ', answer: 'Gi.m4a', image: 'gi.png' },
    { question: 'what-is-phonetic.m4a', lessonUnit: 'qu-quà', answer: 'Qu.m4a', image: 'qu.png' },
  ]],
  ['2', [
    { question: 'what-is-phonetic.m4a', lessonUnit: 'ia-mía', answer: 'ia.m4a', image: 'ia.png' },
    { question: 'what-is-phonetic.m4a', lessonUnit: 'ua-đũa', answer: 'ua.m4a', image: 'ua.png' },
    { question: 'what-is-phonetic.m4a', lessonUnit: 'ưa-dừa', answer: 'uwa.m4a', image: 'uwa.png' },
    { question: 'what-is-phonetic.m4a', lessonUnit: 'ao-chào', answer: 'ao.m4a', image: 'ao.png' },
    { question: 'what-is-phonetic.m4a', lessonUnit: 'eo-chèo', answer: 'eo.m4a', image: 'eo.png' },
    { question: 'what-is-phonetic.m4a', lessonUnit: 'au-bà cháu', answer: 'au.m4a', image: 'au.png' },
    { question: 'what-is-phonetic.m4a', lessonUnit: 'âu-đá cầu', answer: 'aau.m4a', image: 'aau.png' },
    { question: 'what-is-phonetic.m4a', lessonUnit: 'iu-rìu', answer: 'iu.m4a', image: 'iu.png' },
    { question: 'what-is-phonetic.m4a', lessonUnit: 'ưu-cừu', answer: 'uwu.m4a', image: 'uwu.png' },
    { question: 'what-is-phonetic.m4a', lessonUnit: 'ai-lái xe', answer: 'ai.m4a', image: 'ai.png' },
    { question: 'what-is-phonetic.m4a', lessonUnit: 'oi-cái còi', answer: 'oi.m4a', image: 'oi.png' },
    { question: 'what-is-phonetic.m4a', lessonUnit: 'ôi-ngôi sao', answer: 'ooi.m4a', image: 'ooi.png' },
    { question: 'what-is-phonetic.m4a', lessonUnit: 'ơi-xe hơi', answer: 'owi.m4a', image: 'owi.png' },
    { question: 'what-is-phonetic.m4a', lessonUnit: 'ui-túi', answer: 'ui.m4a', image: 'ui.png' },
    { question: 'what-is-phonetic.m4a', lessonUnit: 'ưi-gửi quà', answer: 'uwi.m4a', image: 'uwi.png' },
    { question: 'what-is-phonetic.m4a', lessonUnit: 'ay-đôi giày', answer: 'ay.m4a', image: 'ay.png' },
    { question: 'what-is-phonetic.m4a', lessonUnit: 'ây-sợ dây', answer: 'aay.m4a', image: 'aay.png' },
  ]],
  ['3', [
    { question: 'what-is-phonetic.m4a', lessonUnit: 'ac-lạc đà', answer: 'ac.m4a', image: 'ac.png' },
    { question: 'what-is-phonetic.m4a', lessonUnit: 'âc-quả gấc', answer: 'aac.m4a', image: 'aac.png' },
    { question: 'what-is-phonetic.m4a', lessonUnit: 'ăc-tắc kè', answer: 'awc.m4a', image: 'awc.png' },
    { question: 'what-is-phonetic.m4a', lessonUnit: 'oc-sóc', answer: 'oc.m4a', image: 'oc.png' },
    { question: 'what-is-phonetic.m4a', lessonUnit: 'ôc-gốc cây', answer: 'ooc.m4a', image: 'ooc.png' },
    { question: 'what-is-phonetic.m4a', lessonUnit: 'uc-cây trúc', answer: 'uc.m4a', image: 'uc.png' },
    { question: 'what-is-phonetic.m4a', lessonUnit: 'ưc-lọ mực', answer: 'wc.m4a', image: 'uwc.png' },
    { question: 'what-is-phonetic.m4a', lessonUnit: 'at-hát', answer: 'at.m4a', image: 'at.png' },
    { question: 'what-is-phonetic.m4a', lessonUnit: 'ăt-cắt giấy', answer: 'awt.m4a', image: 'awt.png' },
    { question: 'what-is-phonetic.m4a', lessonUnit: 'ât-bật ti vi', answer: 'aat.m4a', image: 'aat.png' },
    { question: 'what-is-phonetic.m4a', lessonUnit: 'et-đất sét', answer: 'et.m4a', image: 'et.png' },
    { question: 'what-is-phonetic.m4a', lessonUnit: 'êt-tết tóc', answer: 'eet.m4a', image: 'eet.png' },
    { question: 'what-is-phonetic.m4a', lessonUnit: 'it-quả mít', answer: 'it.m4a', image: 'it.png' },
    { question: 'what-is-phonetic.m4a', lessonUnit: 'ot-cái sọt', answer: 'ot.m4a', image: 'ot.png' },
    { question: 'what-is-phonetic.m4a', lessonUnit: 'ôt-lá lốt', answer: 'oot.m4a', image: 'oot.png' },
    { question: 'what-is-phonetic.m4a', lessonUnit: 'ơt-cái thớt', answer: 'owt.m4a', image: 'owt.png' },
    { question: 'what-is-phonetic.m4a', lessonUnit: 'ut-bút', answer: 'ut.m4a', image: 'ut.png' },
    { question: 'what-is-phonetic.m4a', lessonUnit: 'ưt-mứt dừa', answer: 'wt.m4a', image: 'uwt.png' },
  ]]
]);
