import { ILessonQuestion } from '../services/lesson.service';

export const PHONETICS_QUESTIONS: Map<string, ILessonQuestion[]> = new Map<string, ILessonQuestion[]>([
  ['1', [
    {question: '/sound/what-is-phonetic.m4a', lessonUnit: 'a-A', answer: '/sound/A.m4a', image: '/image/a.png', answerPlayTime: 4},
    {question: '/sound/what-is-phonetic.m4a', lessonUnit: 'b-ba', answer: '/sound/B.m4a', image: '/image/b.png', answerPlayTime: 4},
    {question: '/sound/what-is-phonetic.m4a', lessonUnit: 'c-cá', answer: '/sound/C.m4a', image: '/image/c.png', answerPlayTime: 4},
    {question: '/sound/what-is-phonetic.m4a', lessonUnit: 'o', answer: '/sound/O.m4a', image: '/image/o.png', answerPlayTime: 4},
    {question: '/sound/what-is-phonetic.m4a', lessonUnit: 'ơ-bơ', answer: '/sound/ow.m4a', image: '/image/ow.png', answerPlayTime: 4},
    {question: '/sound/what-is-phonetic.m4a', lessonUnit: 'ô-cô', answer: '/sound/oo.m4a', image: '/image/oo.png', answerPlayTime: 4},
    {question: '/sound/what-is-phonetic.m4a', lessonUnit: 'v-vở', answer: '/sound/V.m4a', image: '/image/v.png', answerPlayTime: 4},
    {question: '/sound/what-is-phonetic.m4a', lessonUnit: 'e-bé', answer: '/sound/E.m4a', image: '/image/e.png', answerPlayTime: 4},
    {question: '/sound/what-is-phonetic.m4a', lessonUnit: 'ê-bế', answer: '/sound/ee.m4a', image: '/image/ee.png', answerPlayTime: 4},
    {question: '/sound/what-is-phonetic.m4a', lessonUnit: 'd-dế', answer: '/sound/D.m4a', image: '/image/d.png', answerPlayTime: 4},
    {question: '/sound/what-is-phonetic.m4a', lessonUnit: 'đ-đỗ', answer: '/sound/dd.m4a', image: '/image/dd.png', answerPlayTime: 4},
    {question: '/sound/what-is-phonetic.m4a', lessonUnit: 'i-bi', answer: '/sound/i.m4a', image: '/image/i.png', answerPlayTime: 4},
    {question: '/sound/what-is-phonetic.m4a', lessonUnit: 'k-kệ', answer: '/sound/K.m4a', image: '/image/k.png', answerPlayTime: 4},
    {question: '/sound/what-is-phonetic.m4a', lessonUnit: 'l-lá', answer: '/sound/L.m4a', image: '/image/l.png', answerPlayTime: 4},
    {question: '/sound/what-is-phonetic.m4a', lessonUnit: 'h-hẹ', answer: '/sound/H.m4a', image: '/image/h.png', answerPlayTime: 4},
    {question: '/sound/what-is-phonetic.m4a', lessonUnit: 'n-nơ', answer: '/sound/n.m4a', image: '/image/n.png', answerPlayTime: 4},
    {question: '/sound/what-is-phonetic.m4a', lessonUnit: 'm-me', answer: '/sound/m.m4a', image: '/image/m.png', answerPlayTime: 4},
    {question: '/sound/what-is-phonetic.m4a', lessonUnit: 'u-mũ', answer: '/sound/u.m4a', image: '/image/u.png', answerPlayTime: 4},
    {question: '/sound/what-is-phonetic.m4a', lessonUnit: 'ư-chữ', answer: '/sound/uw.m4a', image: '/image/uw.png', answerPlayTime: 4},
    {question: '/sound/what-is-phonetic.m4a', lessonUnit: 'g-gà', answer: '/sound/g.m4a', image: '/image/g.png', answerPlayTime: 4},
    {question: '/sound/what-is-phonetic.m4a', lessonUnit: 't-tủ', answer: '/sound/t.m4a', image: '/image/t.png', answerPlayTime: 4},
    {question: '/sound/what-is-phonetic.m4a', lessonUnit: 'r-rổ', answer: '/sound/r.m4a', image: '/image/r.png', answerPlayTime: 4},
    {question: '/sound/what-is-phonetic.m4a', lessonUnit: 's-sư tử', answer: '/sound/s.m4a', image: '/image/s.png', answerPlayTime: 7},
    {question: '/sound/what-is-phonetic.m4a', lessonUnit: 'x-xe ngựa', answer: '/sound/x.m4a', image: '/image/x.png', answerPlayTime: 8},
    {question: '/sound/what-is-phonetic.m4a', lessonUnit: 'p-pa nô', answer: '/sound/p.m4a', image: '/image/p.png', answerPlayTime: 8},
    {question: '/sound/what-is-phonetic.m4a', lessonUnit: 'q-que', answer: '/sound/q.m4a', image: '/image/q.png', answerPlayTime: 4},
    {question: '/sound/what-is-phonetic.m4a', lessonUnit: 'y-y sĩ', answer: '/sound/y.m4a', image: '/image/y.png', answerPlayTime: 5},
    {question: '/sound/what-is-phonetic.m4a', lessonUnit: 'ă-ăn', answer: '/sound/aw.m4a', image: '/image/aw.png', answerPlayTime: 4},
    {question: '/sound/what-is-phonetic.m4a', lessonUnit: 'â-ân cần', answer: '/sound/aa.m4a', image: '/image/aa.png', answerPlayTime: 5},
  ]],
  ['2', [
    { question: '/sound/what-is-phonetic.m4a', lessonUnit: 'ch-chợ', answer: '/sound/Ch.m4a', image: '/image/ch.png' },
    { question: '/sound/what-is-phonetic.m4a', lessonUnit: 'kh-khế', answer: '/sound/Kh.m4a', image: '/image/kh.png' },
    { question: '/sound/what-is-phonetic.m4a', lessonUnit: 'gh-ghế', answer: '/sound/Gh.m4a', image: '/image/gh.png' },
    { question: '/sound/what-is-phonetic.m4a', lessonUnit: 'ng-ngủ', answer: '/sound/Ng.m4a', image: '/image/ng.png' },
    { question: '/sound/what-is-phonetic.m4a', lessonUnit: 'ngh-nghệ', answer: '/sound/Ngh.m4a', image: '/image/ngh.png' },
    { question: '/sound/what-is-phonetic.m4a', lessonUnit: 'th-thỏ', answer: '/sound/Th.m4a', image: '/image/th.png' },
    { question: '/sound/what-is-phonetic.m4a', lessonUnit: 'nh-nhà', answer: '/sound/Nh.m4a', image: '/image/nh.png' },
    { question: '/sound/what-is-phonetic.m4a', lessonUnit: 'tr-tre', answer: '/sound/Tr.m4a', image: '/image/tr.png' },
    { question: '/sound/what-is-phonetic.m4a', lessonUnit: 'ph-phở', answer: '/sound/Ph.m4a', image: '/image/ph.png' },
    { question: '/sound/what-is-phonetic.m4a', lessonUnit: 'gi-giá vẽ', answer: '/sound/Gi.m4a', image: '/image/gi.png' },
    { question: '/sound/what-is-phonetic.m4a', lessonUnit: 'qu-quà', answer: '/sound/Qu.m4a', image: '/image/qu.png' },
  ]],
  ['3', [
    { question: '/sound/what-is-phonetic.m4a', lessonUnit: 'ia-mía', answer: '/sound/ia.m4a', image: '/image/ia.png' },
    { question: '/sound/what-is-phonetic.m4a', lessonUnit: 'ua-đũa', answer: '/sound/ua.m4a', image: '/image/ua.png' },
    { question: '/sound/what-is-phonetic.m4a', lessonUnit: 'ưa-dừa', answer: '/sound/uwa.m4a', image: '/image/uwa.png' },
    { question: '/sound/what-is-phonetic.m4a', lessonUnit: 'ao-chào', answer: '/sound/ao.m4a', image: '/image/ao.png' },
    { question: '/sound/what-is-phonetic.m4a', lessonUnit: 'eo-chèo', answer: '/sound/eo.m4a', image: '/image/eo.png' },
    { question: '/sound/what-is-phonetic.m4a', lessonUnit: 'au-bà cháu', answer: '/sound/au.m4a', image: '/image/au.png' },
    { question: '/sound/what-is-phonetic.m4a', lessonUnit: 'âu-đá cầu', answer: '/sound/aau.m4a', image: '/image/aau.png' },
    { question: '/sound/what-is-phonetic.m4a', lessonUnit: 'iu-rìu', answer: '/sound/iu.m4a', image: '/image/iu.png' },
    { question: '/sound/what-is-phonetic.m4a', lessonUnit: 'ưu-cừu', answer: '/sound/uwu.m4a', image: '/image/uwu.png' },
    { question: '/sound/what-is-phonetic.m4a', lessonUnit: 'ai-lái xe', answer: '/sound/ai.m4a', image: '/image/ai.png' },
    { question: '/sound/what-is-phonetic.m4a', lessonUnit: 'oi-cái còi', answer: '/sound/oi.m4a', image: '/image/oi.png' },
    { question: '/sound/what-is-phonetic.m4a', lessonUnit: 'ôi-ngôi sao', answer: '/sound/ooi.m4a', image: '/image/ooi.png' },
    { question: '/sound/what-is-phonetic.m4a', lessonUnit: 'ơi-xe hơi', answer: '/sound/owi.m4a', image: '/image/owi.png' },
    { question: '/sound/what-is-phonetic.m4a', lessonUnit: 'ui-túi', answer: '/sound/ui.m4a', image: '/image/ui.png' },
    { question: '/sound/what-is-phonetic.m4a', lessonUnit: 'ưi-gửi quà', answer: '/sound/uwi.m4a', image: '/image/uwi.png' },
    { question: '/sound/what-is-phonetic.m4a', lessonUnit: 'ay-đôi giày', answer: '/sound/ay.m4a', image: '/image/ay.png' },
    { question: '/sound/what-is-phonetic.m4a', lessonUnit: 'ây-sợ dây', answer: '/sound/aay.m4a', image: '/image/aay.png' },
  ]],
  ['4', [
    { question: '/sound/what-is-phonetic.m4a', lessonUnit: 'ac-lạc đà', answer: '/sound/ac.m4a', image: '/image/ac.png' },
    { question: '/sound/what-is-phonetic.m4a', lessonUnit: 'âc-quả gấc', answer: '/sound/aac.m4a', image: '/image/aac.png' },
    { question: '/sound/what-is-phonetic.m4a', lessonUnit: 'ăc-tắc kè', answer: '/sound/awc.m4a', image: '/image/awc.png' },
    { question: '/sound/what-is-phonetic.m4a', lessonUnit: 'oc-sóc', answer: '/sound/oc.m4a', image: '/image/oc.png' },
    { question: '/sound/what-is-phonetic.m4a', lessonUnit: 'ôc-gốc cây', answer: '/sound/ooc.m4a', image: '/image/ooc.png' },
    { question: '/sound/what-is-phonetic.m4a', lessonUnit: 'uc-cây trúc', answer: '/sound/uc.m4a', image: '/image/uc.png' },
    { question: '/sound/what-is-phonetic.m4a', lessonUnit: 'ưc-lọ mực', answer: '/sound/wc.m4a', image: '/image/uwc.png' },
    { question: '/sound/what-is-phonetic.m4a', lessonUnit: 'at-hát', answer: '/sound/at.m4a', image: '/image/at.png' },
    { question: '/sound/what-is-phonetic.m4a', lessonUnit: 'ăt-cắt giấy', answer: '/sound/awt.m4a', image: '/image/awt.png' },
    { question: '/sound/what-is-phonetic.m4a', lessonUnit: 'ât-bật ti vi', answer: '/sound/aat.m4a', image: '/image/aat.png' },
    { question: '/sound/what-is-phonetic.m4a', lessonUnit: 'et-đất sét', answer: '/sound/et.m4a', image: '/image/et.png' },
    { question: '/sound/what-is-phonetic.m4a', lessonUnit: 'êt-tết tóc', answer: '/sound/eet.m4a', image: '/image/eet.png' },
    { question: '/sound/what-is-phonetic.m4a', lessonUnit: 'it-quả mít', answer: '/sound/it.m4a', image: '/image/it.png' },
    { question: '/sound/what-is-phonetic.m4a', lessonUnit: 'ot-cái sọt', answer: '/sound/ot.m4a', image: '/image/ot.png' },
    { question: '/sound/what-is-phonetic.m4a', lessonUnit: 'ôt-lá lốt', answer: '/sound/oot.m4a', image: '/image/oot.png' },
    { question: '/sound/what-is-phonetic.m4a', lessonUnit: 'ơt-cái thớt', answer: '/sound/owt.m4a', image: '/image/owt.png' },
    { question: '/sound/what-is-phonetic.m4a', lessonUnit: 'ut-bút', answer: '/sound/ut.m4a', image: '/image/ut.png' },
    { question: '/sound/what-is-phonetic.m4a', lessonUnit: 'ưt-mứt dừa', answer: '/sound/wt.m4a', image: '/image/uwt.png' },
  ]]
]);
